// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGYWDY4Si2BygQ9u2us3EmBUzusVZhzOY',
    appId: '1:93094364829:web:75644bd5850839edc03674',
    messagingSenderId: '93094364829',
    projectId: 'libreriaflutter',
    authDomain: 'libreriaflutter.firebaseapp.com',
    databaseURL: 'https://libreriaflutter-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'libreriaflutter.appspot.com',
    measurementId: 'G-5WLB5EZ7RV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCEQ_dO6RCyw31tVLLtEJOK-Q5neejShT4',
    appId: '1:93094364829:android:b8196974245c5980c03674',
    messagingSenderId: '93094364829',
    projectId: 'libreriaflutter',
    databaseURL: 'https://libreriaflutter-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'libreriaflutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0OZmBCWQRkXhpPAqdeLcfHNyHH8N3KXQ',
    appId: '1:93094364829:ios:668b91c7303179bec03674',
    messagingSenderId: '93094364829',
    projectId: 'libreriaflutter',
    databaseURL: 'https://libreriaflutter-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'libreriaflutter.appspot.com',
    iosClientId: '93094364829-0vqt5ugi9pr1dodcefrdpvf3vpda0t4k.apps.googleusercontent.com',
    iosBundleId: 'com.example.libreriaFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA0OZmBCWQRkXhpPAqdeLcfHNyHH8N3KXQ',
    appId: '1:93094364829:ios:668b91c7303179bec03674',
    messagingSenderId: '93094364829',
    projectId: 'libreriaflutter',
    databaseURL: 'https://libreriaflutter-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'libreriaflutter.appspot.com',
    iosClientId: '93094364829-0vqt5ugi9pr1dodcefrdpvf3vpda0t4k.apps.googleusercontent.com',
    iosBundleId: 'com.example.libreriaFlutter',
  );
}
